/**
 * Opens a new window with formatted HTML from markdown and triggers browser print (Save as PDF).
 */
export function downloadMarkdownAsPdf(
  markdown: string,
  title: string,
  subtitle?: string
) {
  // Convert markdown to simple HTML
  let html = markdown
    .replace(/^#### (.+)$/gm, '<h4 style="font-size:14px;font-weight:bold;margin:16px 0 6px;">$1</h4>')
    .replace(/^### (.+)$/gm, '<h3 style="font-size:16px;font-weight:bold;margin:20px 0 8px;">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 style="font-size:20px;font-weight:bold;margin:28px 0 10px;border-bottom:1px solid #ddd;padding-bottom:6px;">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 style="font-size:26px;font-weight:bold;margin:0 0 12px;">$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/^\|(.+)$/gm, (match) => {
      const cells = match.split("|").filter(Boolean).map((c) => c.trim());
      if (cells.every((c) => /^-+$/.test(c))) return "";
      const isHeader = cells.some((c) => c.startsWith("**"));
      const tag = isHeader ? "th" : "td";
      const bg = isHeader ? 'background:#f3f4f6;' : '';
      return `<tr>${cells.map((c) => `<${tag} style="border:1px solid #d1d5db;padding:6px 10px;font-size:13px;${bg}">${c}</${tag}>`).join("")}</tr>`;
    })
    .replace(/^- (.+)$/gm, '<li style="margin-left:20px;font-size:14px;margin-bottom:4px;">$1</li>')
    .replace(/^💡 (.+)$/gm, '<div style="background:#f0f9ff;border:1px solid #bae6fd;border-radius:8px;padding:10px 14px;margin:12px 0;font-size:13px;">💡 $1</div>')
    .replace(/^⚡ (.+)$/gm, '<div style="background:#fef3c7;border:1px solid #fde68a;border-radius:8px;padding:10px 14px;margin:12px 0;font-size:13px;">⚡ $1</div>')
    .replace(/^---$/gm, '<hr style="margin:24px 0;border:none;border-top:1px solid #e5e7eb;" />')
    .replace(/\n\n/g, "<br/>");

  // Wrap table rows
  if (html.includes("<tr>")) {
    html = html.replace(
      /(<tr>.*?<\/tr>)+/gs,
      '<table style="width:100%;border-collapse:collapse;margin:16px 0;">$&</table>'
    );
  }

  const fullHtml = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>${title}</title>
  <style>
    @media print {
      body { margin: 0; }
      @page { margin: 1.5cm; }
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      color: #1a1a1a;
      line-height: 1.6;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      font-size: 14px;
    }
    .header {
      text-align: center;
      margin-bottom: 32px;
      padding-bottom: 20px;
      border-bottom: 2px solid #2563eb;
    }
    .header h1 { font-size: 28px; margin: 0 0 6px; color: #111; }
    .header p { font-size: 14px; color: #6b7280; margin: 0; }
    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      font-size: 12px;
      color: #9ca3af;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    ${subtitle ? `<p>${subtitle}</p>` : ""}
  </div>
  ${html}
  <div class="footer">
    Generated by Digital Moonkey Travel · digitalmoonkey.travel
  </div>
  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`;

  const w = window.open("", "_blank");
  if (w) {
    w.document.write(fullHtml);
    w.document.close();
  }
}
