project_id = "mmnjjmcivgimhatdlrjc"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.sync-bokun-bookings]
    verify_jwt = false
