import { Link } from "react-router-dom";
import PageLayout from "@/components/PageLayout";
import LegalLanguageNotice from "@/components/LegalLanguageNotice";
import { useLanguage, localizedPath } from "@/i18n";
import {
  GUIDE_TOKEN_MIN,
  GUIDE_TOKEN_MAX,
  GUIDE_TOKEN_STEP,
  clampTokens,
  usdFromTokens,
} from "@/lib/guideTokenPricing";

function formatUsd(n: number): string {
  return new Intl.NumberFormat(undefined, { style: "currency", currency: "USD" }).format(n);
}

const spanTok = GUIDE_TOKEN_MAX - GUIDE_TOKEN_MIN;
const thirdTok = spanTok / 3;
const guideTierTokens = {
  essential: {
    min: GUIDE_TOKEN_MIN,
    max: clampTokens(GUIDE_TOKEN_MIN + thirdTok - GUIDE_TOKEN_STEP),
  },
  complete: {
    min: clampTokens(GUIDE_TOKEN_MIN + thirdTok),
    max: clampTokens(GUIDE_TOKEN_MIN + 2 * thirdTok - GUIDE_TOKEN_STEP),
  },
  ultimate: {
    min: clampTokens(GUIDE_TOKEN_MIN + 2 * thirdTok),
    max: GUIDE_TOKEN_MAX,
  },
} as const;

function guidePriceRange(minT: number, maxT: number): string {
  const lo = usdFromTokens(minT);
  const hi = usdFromTokens(maxT);
  if (lo === hi) return formatUsd(lo);
  return `${formatUsd(lo)}–${formatUsd(hi)}`;
}

const Pricing = () => {
  const lang = useLanguage();

  return (
    <PageLayout>
      <section className="pt-28 pb-12 md:pt-32 md:pb-16 bg-secondary">
        <div className="container-grid">
          <h1>Pricing</h1>
          <p className="text-muted-foreground text-sm mt-2">All prices in USD. VAT included where applicable.</p>
        </div>
      </section>

      <section className="section-spacing">
        <div className="container-grid">
          <div className="max-w-3xl space-y-10">
            <LegalLanguageNotice />
            {/* eSIM */}
            <div>
              <h2 className="text-lg font-bold mb-3">eSIM Data Plans</h2>
              <p className="text-sm text-muted-foreground leading-relaxed mb-2">
                Prices vary by destination and data allowance. From 3 USD per plan.
              </p>
              <Link to={localizedPath("/esims", lang)} className="text-sm text-primary hover:underline font-medium">
                See all plans →
              </Link>
            </div>

            {/* AI Itinerary */}
            <div>
              <h2 className="text-lg font-bold mb-3">AI Travel Itinerary</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Day-by-day personalised itinerary generated by AI. Any destination, any language.
              </p>
              <p className="text-base font-bold text-foreground mt-2">$15 per itinerary</p>
            </div>

            {/* AI Guides */}
            <div>
              <h2 className="text-lg font-bold mb-3">AI Travel Guides</h2>
              <p className="text-sm text-muted-foreground leading-relaxed mb-4">
                Pricing is tied to how much of the model context you allocate: you pick a token budget from{" "}
                {GUIDE_TOKEN_MIN.toLocaleString()} to {GUIDE_TOKEN_MAX.toLocaleString()} (steps of {GUIDE_TOKEN_STEP.toLocaleString()}). Larger budgets produce longer, denser guides. The amount you pay scales linearly with that budget, from {formatUsd(usdFromTokens(GUIDE_TOKEN_MIN))} to{" "}
                {formatUsd(usdFromTokens(GUIDE_TOKEN_MAX))}. At checkout, Essential, Complete, and Ultimate are the lower, middle, and upper third of that range (they also match how we label depth for generation).
              </p>
              <div className="space-y-4">
                <div className="bg-secondary rounded-xl p-5">
                  <p className="font-bold text-foreground text-sm">Essential</p>
                  <p className="text-sm text-muted-foreground mt-1">Concise guide focused on key highlights.</p>
                  <p className="text-xs text-muted-foreground mt-2 tabular-nums">
                    {guideTierTokens.essential.min.toLocaleString()}–{guideTierTokens.essential.max.toLocaleString()} tokens
                  </p>
                  <p className="text-base font-bold text-foreground mt-1">
                    {guidePriceRange(guideTierTokens.essential.min, guideTierTokens.essential.max)}
                  </p>
                </div>
                <div className="bg-secondary rounded-xl p-5">
                  <p className="font-bold text-foreground text-sm">Complete</p>
                  <p className="text-sm text-muted-foreground mt-1">Deeper destination coverage—neighborhoods, practical tips, and more.</p>
                  <p className="text-xs text-muted-foreground mt-2 tabular-nums">
                    {guideTierTokens.complete.min.toLocaleString()}–{guideTierTokens.complete.max.toLocaleString()} tokens
                  </p>
                  <p className="text-base font-bold text-foreground mt-1">
                    {guidePriceRange(guideTierTokens.complete.min, guideTierTokens.complete.max)}
                  </p>
                </div>
                <div className="bg-secondary rounded-xl p-5">
                  <p className="font-bold text-foreground text-sm">Ultimate</p>
                  <p className="text-sm text-muted-foreground mt-1">Maximum detail—the fullest guide we offer at the top of the token range.</p>
                  <p className="text-xs text-muted-foreground mt-2 tabular-nums">
                    {guideTierTokens.ultimate.min.toLocaleString()}–{guideTierTokens.ultimate.max.toLocaleString()} tokens
                  </p>
                  <p className="text-base font-bold text-foreground mt-1">
                    {guidePriceRange(guideTierTokens.ultimate.min, guideTierTokens.ultimate.max)}
                  </p>
                </div>
              </div>
              <Link
                to={localizedPath("/travel-guides", lang)}
                className="inline-block text-sm text-primary hover:underline font-medium mt-4"
              >
                Configure token budget &rarr;
              </Link>
            </div>

            {/* Experiences */}
            <div>
              <h2 className="text-lg font-bold mb-3">Travel Experiences</h2>
              <p className="text-sm text-muted-foreground leading-relaxed mb-2">
                Price varies by experience and destination.
              </p>
              <Link to={localizedPath("/experiences", lang)} className="text-sm text-primary hover:underline font-medium">
                See all experiences →
              </Link>
            </div>

            {/* Travel Auth */}
            <div>
              <h2 className="text-lg font-bold mb-3">Travel Authorisation Assistance</h2>
              <p className="text-sm text-muted-foreground leading-relaxed mb-3">
                Personalised assistance with visa, ETA, eVisa and ETIAS applications. Our fee includes the applicable government fee and our assistance service.
              </p>
              <p className="text-sm font-bold text-foreground mb-2">Indicative price ranges (government fee + service fee):</p>
              <ul className="text-sm text-muted-foreground space-y-1.5 mb-3">
                <li>• USA ESTA – from $35</li>
                <li>• Canada eTA – from $25</li>
                <li>• UK ETA – from $30</li>
                <li>• Australia ETA – from $35</li>
                <li>• India eVisa – from $55</li>
                <li>• ETIAS (coming soon) – TBC</li>
              </ul>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Prices vary depending on nationality, destination and type of authorisation. Final price confirmed before payment. For destinations not listed, contact <a href="mailto:hello@digitalmoonkey.travel" className="text-primary hover:underline">hello@digitalmoonkey.travel</a>
              </p>
            </div>


            <div className="border-t border-border pt-6 space-y-4">
              <p className="text-sm text-muted-foreground">
                All payments processed securely by Stripe.
              </p>

              {/* Payment method logos */}
              <div className="flex flex-wrap items-center gap-4 opacity-60">
                {/* Visa */}
                <svg viewBox="0 0 48 32" className="h-7 w-auto" aria-label="Visa">
                  <rect width="48" height="32" rx="4" fill="#1A1F71" />
                  <text x="24" y="20" textAnchor="middle" fill="white" fontSize="14" fontWeight="bold" fontFamily="sans-serif">VISA</text>
                </svg>
                {/* Mastercard */}
                <svg viewBox="0 0 48 32" className="h-7 w-auto" aria-label="Mastercard">
                  <rect width="48" height="32" rx="4" fill="#252525" />
                  <circle cx="19" cy="16" r="8" fill="#EB001B" />
                  <circle cx="29" cy="16" r="8" fill="#F79E1B" />
                  <path d="M24 9.37a8 8 0 0 1 0 13.26 8 8 0 0 1 0-13.26z" fill="#FF5F00" />
                </svg>
                {/* Amex */}
                <svg viewBox="0 0 48 32" className="h-7 w-auto" aria-label="American Express">
                  <rect width="48" height="32" rx="4" fill="#006FCF" />
                  <text x="24" y="18" textAnchor="middle" fill="white" fontSize="7" fontWeight="bold" fontFamily="sans-serif">AMEX</text>
                </svg>
                {/* Apple Pay */}
                <svg viewBox="0 0 48 32" className="h-7 w-auto" aria-label="Apple Pay">
                  <rect width="48" height="32" rx="4" fill="#000" />
                  <text x="24" y="19" textAnchor="middle" fill="white" fontSize="9" fontWeight="500" fontFamily="sans-serif"> Pay</text>
                </svg>
                {/* Google Pay */}
                <svg viewBox="0 0 48 32" className="h-7 w-auto" aria-label="Google Pay">
                  <rect width="48" height="32" rx="4" fill="#fff" stroke="#ddd" />
                  <text x="24" y="19" textAnchor="middle" fill="#5F6368" fontSize="8" fontWeight="500" fontFamily="sans-serif">G Pay</text>
                </svg>
                {/* Powered by Stripe */}
                <svg viewBox="0 0 64 32" className="h-7 w-auto" aria-label="Powered by Stripe">
                  <rect width="64" height="32" rx="4" fill="#635BFF" />
                  <text x="32" y="19" textAnchor="middle" fill="white" fontSize="8" fontWeight="600" fontFamily="sans-serif">stripe</text>
                </svg>
              </div>

              <p className="text-sm text-muted-foreground">
                For questions about pricing contact <a href="mailto:hello@digitalmoonkey.travel" className="text-primary hover:underline">hello@digitalmoonkey.travel</a>
              </p>
            </div>
          </div>
        </div>
      </section>
    </PageLayout>
  );
};

export default Pricing;
