import PageLayout from "@/components/PageLayout";
import LegalLanguageNotice from "@/components/LegalLanguageNotice";

const Terms = () => {
  return (
    <PageLayout>
      <section className="pt-28 pb-12 md:pt-32 md:pb-16 bg-secondary">
        <div className="container-grid">
          <h1>Terms & Conditions</h1>
          <p className="text-muted-foreground text-sm mt-2">Last updated: March 2026</p>
        </div>
      </section>

      <section className="section-spacing">
        <div className="container-grid">
          <div className="max-w-3xl space-y-8">
            <LegalLanguageNotice />
            <p className="text-sm leading-relaxed">
              These Terms and Conditions govern your use of digitalmoonkey.travel and all purchases made through our platform.
            </p>

            <div className="bg-secondary rounded-xl p-6 space-y-1 text-sm">
              <p className="font-bold text-foreground">Digital Moonkey Limited</p>
              <p className="text-muted-foreground">Registered in England & Wales</p>
              <p className="text-muted-foreground">Company No. 15716386</p>
              <p className="text-muted-foreground">71-75 Shelton Street, Covent Garden, London, WC2H 9JQ</p>
              <p className="text-muted-foreground">Email: hello@digitalmoonkey.travel</p>
            </div>

            <div className="space-y-6">
              <div>
                <h2 className="text-lg font-bold mb-3">1. Acceptance of Terms</h2>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  By accessing or using digitalmoonkey.travel, you agree to be bound by these Terms and Conditions. If you do not agree, please do not use our platform.
                </p>
              </div>

              <div>
                <h2 className="text-lg font-bold mb-3">2. Our Services</h2>
                <p className="text-sm leading-relaxed text-muted-foreground mb-3">Digital Moonkey Limited provides the following services:</p>
                <div className="space-y-3 text-sm text-muted-foreground">
                  <p><strong className="text-foreground">a) eSIM Data Plans</strong> — digital eSIM cards for international data connectivity, delivered electronically via QR code.</p>
                  <p><strong className="text-foreground">b) AI Travel Itineraries</strong> — personalised day-by-day travel itineraries generated by artificial intelligence, delivered as digital documents.</p>
                  <p><strong className="text-foreground">c) AI Travel Guides</strong> — comprehensive destination guides generated by artificial intelligence, delivered as digital PDF documents.</p>
                  <p><strong className="text-foreground">d) Travel Experiences</strong> — curated tours and activities. Digital Moonkey Limited acts as merchant of record for all experience bookings. Payment is collected by Digital Moonkey Limited.</p>
                  <p><strong className="text-foreground">e) Travel Authorisation Assistance (ESTA/eVisa)</strong> — assistance service for travel authorisation applications. We are an independent assistance service and are not affiliated with any government agency. Official applications can be made directly at government websites free of charge or at lower cost.</p>
                  <p><strong className="text-foreground">f) Digital Moonkey Club</strong> — monthly subscription membership providing access to unlimited AI itineraries, AI travel guides, and member discounts.</p>
                </div>
              </div>

              <div>
                <h2 className="text-lg font-bold mb-3">3. Pricing</h2>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  All prices are displayed in Euros (EUR) and include applicable VAT where required. Prices are subject to change without notice. The price displayed at checkout is the final price you will pay.
                </p>
              </div>

              <div>
                <h2 className="text-lg font-bold mb-3">4. Payment</h2>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  All payments are processed securely by Stripe. We accept major credit and debit cards, Apple Pay and Google Pay. Digital Moonkey Limited is the merchant of record for all transactions. Your card statement will show a charge from Digital Moonkey Limited.
                </p>
              </div>

              <div>
                <h2 className="text-lg font-bold mb-3">5. Digital Products — Delivery</h2>
                <div className="space-y-2 text-sm text-muted-foreground">
                  <p><strong className="text-foreground">eSIM products:</strong> delivered via QR code to your registered email address within minutes of payment confirmation. Delivery may take up to 24 hours in exceptional cases.</p>
                  <p><strong className="text-foreground">AI Itineraries and Travel Guides:</strong> generated and delivered within your account and by email immediately after payment, typically within 60 seconds.</p>
                  <p><strong className="text-foreground">Travel Authorisation Assistance:</strong> processing times vary depending on the type of authorisation and destination government processing times. We will keep you informed by email.</p>
                </div>
              </div>

              <div>
                <h2 className="text-lg font-bold mb-3">6. Cancellations and Refunds</h2>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  Please refer to our full <a href="/refunds" className="text-primary hover:underline">Refund Policy</a> at digitalmoonkey.travel/refunds
                </p>
              </div>

              <div>
                <h2 className="text-lg font-bold mb-3">7. Travel Authorisation Disclaimer</h2>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  Our travel authorisation assistance service (ESTA, eVisa and similar) is an independent assistance service. We are not a government agency or affiliated with any government. The applicable government fees are included in our service fee. Customers can apply directly through official government portals. We make no guarantee of approval as decisions rest solely with the relevant government authority.
                </p>
              </div>

              <div>
                <h2 className="text-lg font-bold mb-3">8. eSIM Compatibility</h2>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  eSIM products require an eSIM-compatible and unlocked device. It is the customer's responsibility to verify device compatibility before purchase. We provide a compatibility checker on the product page. Non-compatible device purchases are non-refundable unless we are at fault.
                </p>
              </div>

              <div>
                <h2 className="text-lg font-bold mb-3">9. AI-Generated Content</h2>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  Our AI itineraries and travel guides are generated using artificial intelligence. While we strive for accuracy, information such as opening hours, prices and availability of places mentioned may change. Always verify critical information independently before travel. We accept no liability for decisions made solely based on AI-generated content.
                </p>
              </div>

              <div>
                <h2 className="text-lg font-bold mb-3">10. Intellectual Property</h2>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  All content on digitalmoonkey.travel, including but not limited to text, graphics, logos and AI-generated content sold through our platform, is the property of Digital Moonkey Limited or its licensors. You may not reproduce, distribute or create derivative works without our express written permission.
                </p>
              </div>

              <div>
                <h2 className="text-lg font-bold mb-3">11. Limitation of Liability</h2>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  To the maximum extent permitted by applicable law, Digital Moonkey Limited shall not be liable for any indirect, incidental, special or consequential damages arising from your use of our services. Our total liability shall not exceed the amount paid by you for the specific service giving rise to the claim.
                </p>
              </div>

              <div>
                <h2 className="text-lg font-bold mb-3">12. Governing Law</h2>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  These Terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.
                </p>
              </div>

              <div>
                <h2 className="text-lg font-bold mb-3">13. Changes to Terms</h2>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  We reserve the right to modify these Terms at any time. Changes will be posted on this page with an updated date. Continued use of our platform constitutes acceptance of the revised Terms.
                </p>
              </div>

              <div>
                <h2 className="text-lg font-bold mb-3">14. Contact</h2>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  For any queries regarding these Terms, contact us at: <a href="mailto:hello@digitalmoonkey.travel" className="text-primary hover:underline">hello@digitalmoonkey.travel</a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </PageLayout>
  );
};

export default Terms;
